@extends('layouts.Layout')

@section('title', 'Aviso de Privacidad')

@section('contenido')
    <div class="container mt-5 mb-md-4 py-5">
        <div class="row justify-content-center">
            <!-- Page content-->
            <div class="col-md-9">
                <!-- Breadcrumb-->
                <nav class="mb-3 pt-md-3" aria-label="Breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('inicio') }}">Inicio</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Aviso de Privacidad</li>
                    </ol>
                </nav>
                <!-- Title-->
                <div class="mb-4">
                    <h1 class="h2 mb-0 text-center">Aviso de Privacidad</h1>
                </div>
                <!-- Basic info-->
                <section class="card card-body border-0 shadow-sm p-4 mb-4" id="basic-info">
                    <p style="text-align: justify;">APTOCLICK SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE (SAPI DE CV), escritura n.147,775, libro 3,083 empresas constituida y existente de conforme a las leyes de México, con domicilio fiscal en Calle Victor Hugo, numero exterior 18, Benito Juarez, Ciudad de Mexico 03570 con RFC APT200604DU y IDCIF 20060141957, es responsable de recabar sus datos personales, así como del tratamiento que se les da a los mismos y de su adecuada protección.</p>
                    <p style="text-align: justify;">Proteger su privacidad es muy importante para nosotros. Es por ello, que nuestra presencia en Internet está diseñada para que, en principio, se pueda usar de forma anónima. Tratamos la información que recibimos y guardamos cuando visita nuestra página web y/o aplicación únicamente con fines de promoción del inmueble objeto de la prestación de servicios en medios impresos y/o electrónicos, bolsas inmobiliarias, publicaciones propiedad de APTOCLICK SAPI DE CV y demás relacionados con la compraventa con de promesa de compra plurianual. Asimismo conservamos sus datos de identificación para futuras operaciones inmobiliarias o de promoción.</p>
                    <p style="text-align: justify;">En ese mismo sentido, utilizamos su información para la elaboración de cualquiera de los siguientes documentos para contrato de compraventa con promesa de compra: 
                    (i) su historial crediticio, y (ii) operaciones crediticias y otras de naturaleza análoga que mantengan o hayan mantenido con entidades financieras y empresas comerciales; la calificación de créditos o de riesgo; la verificación y/o confirmación de identidad o de datos generales; alertas, monitoreo del comportamiento crediticio, así como la recopilación, clasificación, manejo y envío de información crediticia o de información relacionada con ésta que incida o pueda incidir en la determinación del comportamiento crediticio y capacidad de pago, así como realizar simulaciones internas de: (i) créditos hipotecarios para la compra de una propiedad (iiI) refinanciamiento de hipoteca; (iv) obtención de créditos de liquidez con garantía hipotecaria, (v) créditos de remodelación y/o construcción; asesoría para iniciar el trámite de aprobación del crédito respectivo con la(s) entidad(es) financiera(s) seleccionada(s)
                    </p>
                    <p style="text-align: justify;">Con el fin de informarle sobre las políticas y actividades en relación con la obtención, uso y transferencia de sus Datos Personales en sitios de Internet o de forma física, APTOCLICK SAPI DE CV está consciente de sus obligaciones ante la Ley Federal de Protección de Datos Personales en Posesión de Particulares, su reglamento y demás lineamientos que conjuntamente integran la regulación de protección de datos personales, y considera importante salvaguardar la privacidad personal, por lo que pone a su disposición esta Política de Privacidad.</p>
                    <p style="text-align: justify;">Esta Política de Privacidad detalla la manera en la que APTOCLICK SAPI DE CV y sus funcionarios, representantes, empleados, proveedores, así como otras entidades que actúan en representación de, en coparticipación, como aliados estratégicos y/o con la autorización de APTOCLICK SAPI DE CV para la obtención, protección, uso y transferencia de su información recabada en nuestra página web, mediante correo electrónico o de manera física o presencial, con estricto apego a lo establecido en el Aviso de Privacidad respectivo, así como a la presente Política de Privacidad.</p>
                    <p style="text-align: justify;">Al hacer uso de la Página Web, otorga su consentimiento para que APTOCLICK SAPI DE CV. procese sus datos personales y/o los transfiera a sus subsidiarias y/o afiliadas, así como a las personas que APTOCLICK SAPI DE CV considere competentes para procesar la información aquí recabada, dentro del margen de los fines descritos en la presente política de privacidad y el correspondiente aviso de privacidad.</p>
                    <p style="text-align: justify;"><strong>1. Obtención de Información (incluyendo Datos Personales)</strong></p>
                    <p style="text-align: justify;">A pesar de que no es necesario proporcionar Datos Personales para ingresar a la Página Web, para utilizar ciertas funciones de nuestro sitio de internet, recabamos cierta información no-personal de manera automática, incluyendo pero sin limitar a direcciones IP, clase de buscador, sitios web de referencia, cookies y horarios de acceso, sin que pueda esta información volverlo identificable, de conformidad con los términos establecidos en la Ley Federal de Protección de Datos Personales en Posesión de Particulares. La información antes mencionada es recabada para fines estadísticos.</p>
                    <p style="text-align: justify;">La entrega de sus Datos Personales a APTOCLICK SAPI DE CV es voluntaria, y en muchos casos necesaria para la entera funcionalidad de todos los servicios que provee nuestra Página Web. En caso de que usted no proporcione dichos Datos Personales, APTOCLICK SAPI DE CV se encontrará imposibilitado de proveer el servicio entero de la Página Web. Entre los datos recabados están: nombre, dirección, fecha de nacimiento, correo electrónico, número de teléfono, y género.</p>
                    <p style="text-align: justify;">Las finalidades con las que son recabados sus Datos Personales son las siguientes:</p>
                    <ol style="text-align: justify;">
                        <li>Elaboración de cualquiera de los siguientes documentos para la compraventa con promesa de compra:
                        
                        <ul>
                            <li>Contrato de compraventa con promesa de compra.</li>
                            <li>Revisión su historial crediticio, y operaciones crediticias y otras de naturaleza análoga que mantengan o hayan mantenido con entidades financieras y empresas comerciales; la calificación de créditos o de riesgo; la verificación y/o confirmación de identidad o de datos generales; alertas, monitoreo del comportamiento crediticio, así como la recopilación, clasificación, manejo y envío de información crediticia o de información relacionada con ésta que incida o pueda incidir en la determinación del comportamiento crediticio y capacidad de pago, así como realizar simulaciones internas de: (i) créditos hipotecarios para la compra de una propiedad (ii) refinanciamiento de hipoteca; (iii) obtención de créditos de liquidez con garantía hipotecaria, (iv) créditos de remodelación y/o construcción; asesoría para iniciar el trámite de aprobación del crédito respectivo con la(s) entidad(es) financiera(s) seleccionada(s).</li>
                            
                            <li>Cualquier otro documento que sea necesario para una operación compraventa con promesa de compra.</li>
                        </ul>
                        </li>
                        <li>Promoción del inmueble en medios impresos o electrónicos, bolsas inmobiliarias, publicaciones propiedad de APTOCLICK SAPI DE CV y demás relacionados con el arrendamiento con opción a compra del inmueble.</li>
                        <li>Conservación de sus datos de identificación para futuras operaciones inmobiliarias o de promoción por parte de APTOCLICK SAPI DE CV.</li>
                    </ol>
                    <p style="text-align: justify;">De igual forma, podremos solicitar, de manera voluntaria para los visitantes de nuestra Página Web, sus opiniones respecto a nuestros servicios y Página Web, así como de sus preferencias, gustos, y demás información que nos permitan proveer un mejor servicio. Esta información será utilizada de manera exclusiva para fines estadísticos, de mercadotecnia y estratégicos para ofrecer mejores servicios. APTOCLICK SAPI DE CV podrá utilizar distintos sistemas, servicios y/o productos para procesar la información obtenida del uso de la Página Web.</p>
                    <p style="text-align: justify;"><strong>1.1. Uso de Cookies y otras tecnologías</strong></p>
                    <p style="text-align: justify;">La Página Web utiliza cookies, mismos que podrán ser negados por Usted como visitante de la Página Web mediante los ajustes correspondientes al explorador. El uso de cookies es indispensable para el funcionamiento completo de la Página Web y su contenido, mejorando la experiencia del usuario. Estas cookies pueden ser almacenadas en el dispositivo que se esté usando para visitar la Página Web.</p>
                    <p style="text-align: justify;">Es posible que Nosotros nos veamos en la necesidad de solicitar Datos Personales Sensibles para las finalidades que en su caso se indiquen en el aviso de privacidad respectivo, situación que les será informada a efecto de obtener su consentimiento de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de Particulares.</p>
                    <p style="text-align: justify;">APTOCLICK SAPI DE CV podrá utilizar otras tecnologías que funcionen a la par de, o que tengan funciones similares a las cookies de las cuales obtenga información de los visitantes de la Página Web, mismas que podrán estar incluidas en mensajes o boletines, a efecto de determinar si los mensajes fueron abiertos, tales como web beacons o similares.</p>
                    <p style="text-align: justify;"><strong>2. Uso de Datos Personales obtenidas en la Página Web</strong></p>
                    <p style="text-align: justify;">La información proporcionada a APTOCLICK SAPI DE CV. se utilizará para los fines arriba señalados, y no se comercializará ni se transferirá a terceros diferentes a los arriba señalados, o a los fines establecidos en los avisos de privacidad que lleguen a tener lugar. APTOCLICK SAPI DE CV, o los terceros que reciban la información de conformidad con esta Política, podrán utilizar y procesar tanto los Datos Personales, como la información que no haga identificable al usuario de la Página Web, de forma individual o colectiva para los fines arriba señalados.</p>
                    <p style="text-align: justify;"><strong>3. Transferencia de Datos Personales</strong></p>
                    <p style="text-align: justify;">Salvo por que sea dispuesto de manera distinta en la presente Política o en el aviso de privacidad respectivo, los Datos Personales recabados por APTOCLICK SAPI DE CV. se utilizarán para los fines para los que fueron proporcionados, y serán transferidos únicamente a las empresas filiales o subsidiarias de APTOCLICK SAPI DE CV y a cada una de las áreas que las integran, así como a las empresas que APTOCLICK SAPI DE CV contrate para procesar y analizar dicha información. El receptor de su información, será solicitado por Nosotros de tratar los Datos Personales con los mismos niveles de seguridad que con los que nosotros los tratamos.</p>
                    <p style="text-align: justify;"><strong>4. Datos Personales de Menores de Edad</strong></p>
                    <p style="text-align: justify;">Para el caso de la obtención de Datos Personales de menores de edad, se deberá de contar con el consentimiento del padre, madre o tutor, y se deberá de proporcionar copia de la documentación que acredite dicha relación, de manera enunciativa más no limitativa, acta de nacimiento e identificaciones.</p>
                    <p style="text-align: justify;"><strong>5. Medidas De Seguridad</strong></p>
                    <p style="text-align: justify;">APTOCLICK SAPI DE CV protege y continuará protegiendo sus Datos Personales con todos los esfuerzos razonables para asegurarse que aquellos recabados en la Página Web o de cualquier otra manera, cumplen con lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de Particulares. No obstante lo anterior, sugerimos que la persona que visita la Página Web también cuente con medidas adicionales para proteger su información personal. APTOCLICK SAPI DE CV no se hace responsable por el acceso del visitante a la Página Web a links de terceros de cuyas políticas de privacidad APTOCLICK SAPI DE CV no tenga control.</p>
                    <p style="text-align: justify;"><strong>6. Revisión y Actualización De La Información Recabada</strong></p>
                    <p style="text-align: justify;">Los visitantes de la Página Web que provean Datos Personales a APTOCLICK SAPI DE CV, podrán ejercer sus derechos de acceso, rectificación, cancelación y oposición, de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de Particulares en cualquier momento contactando a APTOCLICK SAPI DE CV.</p>
                    <p style="text-align: justify;"><strong>7. Actualizaciones A Esta Política De Privacidad</strong></p>
                    <p style="text-align: justify;">APTOCLICK SAPI DE CV se reserva el derecho de actualizar, ajustar, y modificar estas Políticas en cualquier momento y sin previo aviso. De igual manera, podremos cambiar los servicios, productos, políticas, promociones y/o fines de esta Página Web sin previo aviso. Lo invitamos a revisar los cambios a esta Política de manera regular.</p>
                    <p style="text-align: justify;"><strong>8. Contacto</strong></p>
                    <p style="text-align: justify;">Cualquier duda o comentario a las presentes Políticas puede ser atendido, enviando un correo a aptoclick@gmail.com.</p>
                    <p style="text-align: justify;">Esta política de privacidad ha sido actualizada el 05 de Diciembre 2021</p>
                </section>
            </div>
        </div>
    </div>
@endsection
